openapi: 3.0.3
info:
  title: Create Subscription For OECD Tax Pillar 2 Service
  description: A synchronous API that allows MDTP / BTA to post requests to ETMP in order for subscriptions to be created for OECD Pillar 2 customers.
  version: 1.1.0
  contact:
    name: Enterprise Integration Services
    email: services.enterpriseintegration@hmrc.gov.uk
  x-integration-catalogue:
    reviewed-date: '2023-08-05'
    platform: CORE_IF
    publisher-reference: API#2142
    short-description: A synchronous API that allows MDTP / BTA to post requests to ETMP in order for subscriptions to be created for OECD Pillar 2 customers.
    status: LIVE
    backends:
      - ETMP
servers:
  - url: 'https://{hostname}:{port}'
    description: Actual environment values can be obtained from IF platforms team for each environment
tags:
  - name: API#2142
    description: A synchronous API that allows MDTP / BTA to post requests to ETMP in order for subscriptions to be created for OECD Pillar 2 customers..
paths:
  '/pillar2/subscription':
    post:
      summary: 'API#2142 Create Subscription For OECD Tax Pillar 2 Service'
      description: |
      
        Example: /pillar2/subscription
        ```
        Change Log
        ```

          | Version | Date | Author | Description |
          |---|-----|------|-----|
          | 0.1.0  | 26-07-2023 | Audu Alfa  | Initial draft |
          |---|-----|------|-----|
          | 1.0.0  | 02-08-2023 | Audu Alfa  | Baselined Version |
          | 1.1.0  | 05-08-2023 | Audu Alfa  | Updated the folliwing: |
          |||| - parameters > correlationId > description |
          |||| - Added 'GB' to the countryCode enum list |
          |||| - Updated request example to inlcude telephone numbers as strings |
          | 1.2.0  | 05-08-2023 | Audu Alfa  | Updated the folliwing:|
          |||| - Removed originator id from parameters section|
          |||| - Removed 400 http response - 'invalid or missing regime'|
          |||| - Removed '/' at the end of url path resulting in '/pillar2/subscription' |
          
      operationId: createSubscriptionPillar2
      tags:
        - API#2142
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/environment'
        - $ref: '#/components/parameters/correlationId'
      requestBody:  
        required: true
        description: Request body
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/request'
            examples:
              Example1:
                summary: Full Request Payload Including Optional Fields.
                value:
                  upeDetails: 
                    safeId: 'XK2292282712548'
                    customerIdentification1: 'SA7743248'
                    customerIdentification2: '1234567890'
                    organisationName: 'Acme Ltd'
                    registrationDate: '1994-12-05'
                    domesticOnly: true
                    filingMember: false
                  accountingPeriod:
                    startDate: '2022-04-06'
                    endDate: '2023-04-05'
                  upeCorrespAddressDetails:
                    addressLine1: '10 High Street'
                    addressLine2: 'Egham'
                    addressLine3: 'Surrey'
                    addressLine4: 'South East England'
                    postCode: 'SU10 6HH'
                    countryCode: 'GB'
                  primaryContactDetails:
                    name: 'Fred Jones'
                    telephone: '01159700700'
                    emailAddress: 'fred.jone@acme.com'
                  secondaryContactDetails:
                    name: 'Jill Jones'
                    telephone: '01159788799'
                    emailAddress: 'jill.jone@acme.com'
                  filingMemberDetails: 
                    safeId: 'XV5277988337712'
                    customerIdentification1: 'DD17743248'
                    customerIdentification2: '431234567890'
                    organisationName: 'Acme Upe Ltd'
      responses:
        '201':
          description: Success Response
          headers:
            CorrelationId:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/successResponse'
              examples:
                Success Response:
                  value:
                    success:
                      processingDate: '2022-01-31T09:26:17Z'
                      formBundleNumber: '119000004320'
                      plrReference: 'XMPLR0012345678'
        '400':
          description: |-
            Bad Request
            ```
            A bad request has been made; this could be due to one or more issues with the request

            "code"                   "reason"
            INVALID_CORRELATIONID     Submission has not passed validation. Invalid Header CorrelationId.
            INVALID_PAYLOAD           Submission has not passed validation. Invalid Payload.
          headers:
            CorrelationId:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Bad request - single code sample:
                  value:
                    failures:
                      - code: INVALID_PAYLOAD
                        reason: Submission has not passed validation. Invalid Payload.
                Bad request - Multiple Error Codes:
                  value:
                    failures:
                      - code: INVALID_CORRELATIONID
                        reason: Submission has not passed validation. Invalid Header CorrelationId.
                      - code: INVALID_PAYLOAD
                        reason: Submission has not passed validation. Invalid Payload.
        '404':
          description: |
            Not found at back-end
            ```
            "code"                     "reason"
            BUSINESS_PARTNER_NOT_FOUND  The backend has rejected the request due to no business partner being found against the ID supplied.
          headers:
            CorrelationId:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Identifier not found sample:
                  summary: Single Error Code
                  value:
                    failures:
                      - code: BUSINESS_PARTNER_NOT_FOUND
                        reason: The backend has rejected the request due to no business partner being found against the ID supplied.
        '409':
          description: |
            Duplicate Record at back-end
            ```
            "code"                     "reason"
            DUPLICATE_ACK_REF           The backend has rejected the request due to a duplicate acknowledgement reference already existing.
            SUBSCRIPTION_CONFLICT       The backend has rejected the request due to the business partner already having a SUBSCRIPTION for this regime.
          headers:
            CorrelationId:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Identifier not found sample:
                  summary: Single Error Code
                  value:
                    failures:
                      - code: DUPLICATE_ACK_REF 
                        reason: The backend has rejected the request due to a duplicate acknowledgement reference already existing.
        '422':
          description: |
            Duplicate Record at back-end
            ```
            "code"                                    "reason"
            UNABLE_TO_GENERATE_OECD_REFERENCE         The backend has indicated that it is unable to generate the OECD reference.
            REQUEST_NOT_PROCESSED                     The backend has indicated that the request could not be processed.
          headers:
            CorrelationId:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Identifier not found sample:
                  summary: Single Error Code
                  value:
                    failures:
                      - code: UNABLE_TO_GENERATE_OECD_REFERENCE
                        reason: The backend has indicated that it is unable to generate the OECD reference.
        '500':
          description: |-
            Server Error
            ```
            "code"         "reason"
            SERVER_ERROR   IF is currently experiencing problems that require live service intervention.
          headers:
            CorrelationId:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Actual response:
                  value:
                    failures:
                      - code: SERVER_ERROR
                        reason: IF is currently experiencing problems that require live service intervention.
        '503':
          description: |-
            Service unavailable
            ```
            "code"               "reason"
            SERVICE_UNAVAILABLE  Dependent systems are currently not responding.
          headers:
            CorrelationId:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Actual response:
                  value:
                    failures:
                      - code: SERVICE_UNAVAILABLE
                        reason: Dependent systems are currently not responding.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  headers:
    CorrelationId:
      description: CorrelationID - Used for traceability purposes when present
      schema:
        type: string
        pattern: '^[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}$'
    Content-Type:
      description: Tells the client what the content type of the returned content actually is
      schema:
        type: string
        enum:
          - application/json
  parameters:
    environment:
      in: header
      name: Environment
      description: Mandatory. The environment in use.
      required: true
      schema:
        type: string
        enum:
          - ist0
          - clone
          - live
    correlationId:
      in: header
      name: CorrelationId
      description: Strongly recommended. A UUID format string for the transaction.
      required: false
      schema:
        type: string
        pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
  schemas:
    request:
      title: API#2142 Create Subscription For OECD Tax Pillar 2 Service Request Schema
      type: object
      additionalProperties: false
      required: 
        - upeDetails
        - accountingPeriod
        - upeCorrespAddressDetails
        - primaryContactDetails
      properties:
        upeDetails: 
          type: object
          additionalProperties: false
          required:
            - safeId
            - organisationName
            - registrationDate
            - domesticOnly
            - filingMember
          properties:
            safeId: 
              type: string
              description: Safe ID.
              pattern: '^X[A-Z]{1}[0-9]{13}$'
            customerIdentification1: 
              type: string
              description: Customer Identification 1 - CRN.
              pattern: '^[A-Za-z0-9]{1,15}$'
            customerIdentification2: 
              type: string
              description: Customer Identification 2 - CT UTR.
              pattern: '^[A-Za-z0-9]{1,15}$'
            organisationName: 
              type: string
              description: Registered name of the organisation.
              minLength: 1
              maxLength: 160
            registrationDate: 
              allOf:
                - $ref: '#/components/schemas/dateType'
                - description: Registration date
            domesticOnly:  
              type: boolean
              description: Boolean to indicate the organisation is UK domestic only.
            filingMember: 
              type: boolean
              description: Boolean to indicate filing member.
        accountingPeriod: 
          type: object
          additionalProperties: false
          required: 
            - startDate
            - endDate
          properties:
            startDate:  
              allOf:
                - $ref: '#/components/schemas/dateType'
                - description: Start date of accounting period
            endDate:  
              allOf:
                - $ref: '#/components/schemas/dateType'
                - description: End date of accounting period
        upeCorrespAddressDetails: 
          type: object
          additionalProperties: false
          required: 
           - addressLine1
           - countryCode
          properties:
            addressLine1:
              type: string
              minLength: 1
              maxLength: 35
              description: Address Line 1
            addressLine2:
              type: string
              minLength: 1
              maxLength: 35
              description: Address Line 2
            addressLine3:
              type: string
              minLength: 1
              maxLength: 35
              description: Address Line 3
            addressLine4:
              type: string
              minLength: 1
              maxLength: 35
              description: Address Line 4
            postCode:
              type: string
              minLength: 1
              maxLength: 10
              description: Postal code
            countryCode:
              $ref: '#/components/schemas/countryCodeType'
        primaryContactDetails: 
          $ref: '#/components/schemas/contactDetailsType'
        secondaryContactDetails: 
          $ref: '#/components/schemas/contactDetailsType'
        filingMemberDetails: 
          type: object
          additionalProperties: false
          required:
            - safeId
            - organisationName
          properties:
            safeId: 
              type: string
              description: Safe ID.
              pattern: '^X[A-Z]{1}[0-9]{13}$'
            customerIdentification1: 
              type: string
              description: Customer Identification 1 - CRN.
              pattern: '^[A-Za-z0-9]{1,15}$'
            customerIdentification2: 
              type: string
              description: Customer Identification 2 - CT UTR.
              pattern: '^[A-Za-z0-9]{1,15}$'
            organisationName: 
              type: string
              description: Registered name of the organisation.
              minLength: 1
              maxLength: 160
    errorResponse:
      title: API#2142 Create Subscription For OECD Tax Pillar 2 Service Error Response Schema
      type: object
      additionalProperties: false
      required:
        - failures
      properties:
        failures:
          type: array
          minItems: 1
          uniqueItems: true
          items:
            type: object
            additionalProperties: false
            required:
              - code
              - reason
            properties:
              code:
                description: Keys for all the errors returned
                type: string
                pattern: '^[A-Z0-9_-]{1,160}$'
              reason:
                description: A simple description for the failure
                type: string
                minLength: 1
                maxLength: 160
    successResponse:
      title: API#2142 Create Subscription For OECD Tax Pillar 2 Service Success Response Schema
      type: object
      additionalProperties: false
      required:
        - success
      properties:
        success:
          type: object
          additionalProperties: false
          required:
            - processingDate
            - formBundleNumber
            - plrReference
          properties: 
            processingDate: 
              type: string
              pattern: "^[0-9]{4}-([0][1-9]|[1][0-2])-([0][1-9]|[1-2][0-9]|[3][0-1])T([0-1][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]Z$"
            formBundleNumber: 
              type: string
              minLength: 12
              maxLength: 12
              pattern: "^[0-9]{12}$"
            plrReference:
              type: string
              minLength: 15
              maxLength: 15
              pattern: "^X[A-Z]{1}PLR[0-9]{10}$"
    contactDetailsType:
      type: object
      additionalProperties: false
      required: 
        - name
        - emailAddress
      properties: 
        name:
          type: string
          minLength: 1
          maxLength: 160
          description: Name
        telephone: 
          type: string
          pattern: "^(?:(?:\\(?(?:00|\\+)([1-4]\\d\\d|[1-9]\\d?)\\)?)?[\\-\\.\\ \\/]?)?((?:\\(?\\d{1,}\\)?[\\-\\.\\ \\/]?){0,})(?:[\\-\\.\\ \\/]?(?:#|ext\\.?|extension|x)[\\-\\.\\ \\/]?(\\d+))?$"
        emailAddress:
          type: string
          format: email
    dateType: 
      type: string
      format: date
    countryCodeType: 
      description: Country code iso 3166-1 alpha-2
      type: string
      enum:
        - AD
        - AE
        - AF
        - AG
        - AI
        - AL
        - AM
        - AN
        - AO
        - AQ
        - AR
        - AS
        - AT
        - AU
        - AW
        - AX
        - AZ
        - BA
        - BB
        - BD
        - BE
        - BF
        - BG
        - BH
        - BI
        - BJ
        - BM
        - BN
        - BO
        - BQ
        - BR
        - BS
        - BT
        - BV
        - BW
        - BY
        - BZ
        - CA
        - CC
        - CD
        - CF
        - CG
        - CH
        - CI
        - CK
        - CL
        - CM
        - CN
        - CO
        - CR
        - CS
        - CU
        - CV
        - CW
        - CX
        - CY
        - CZ
        - DE
        - DJ
        - DK
        - DM
        - DO
        - DZ
        - EC
        - EE
        - EG
        - EH
        - ER
        - ES
        - ET
        - EU
        - FC
        - FI
        - FJ
        - FK
        - FM
        - FO
        - FR
        - GA
        - GB
        - GD
        - GE
        - GF
        - GG
        - GH
        - GI
        - GL
        - GM
        - GN
        - GP
        - GQ
        - GR
        - GS
        - GT
        - GU
        - GW
        - GY
        - HK
        - HM
        - HN
        - HR
        - HT
        - HU
        - ID
        - IE
        - IL
        - IM
        - IN
        - IO
        - IQ
        - IR
        - IS
        - IT
        - JE
        - JM
        - JO
        - JP
        - KE
        - KG
        - KH
        - KI
        - KM
        - KN
        - KP
        - KR
        - KW
        - KY
        - KZ
        - LA
        - LB
        - LC
        - LI
        - LK
        - LR
        - LS
        - LT
        - LU
        - LV
        - LY
        - MA
        - MC
        - MD
        - ME
        - MF
        - MG
        - MH
        - MK
        - ML
        - MM
        - MN
        - MO
        - MP
        - MQ
        - MR
        - MS
        - MT
        - MU
        - MV
        - MW
        - MX
        - MY
        - MZ
        - NA
        - NC
        - NE
        - NF
        - NG
        - NI
        - NL
        - NO
        - NP
        - NR
        - NT
        - NU
        - NZ
        - OM
        - OR
        - PA
        - PE
        - PF
        - PG
        - PH
        - PK
        - PL
        - PM
        - PN
        - PR
        - PS
        - PT
        - PW
        - PY
        - QA
        - RE
        - RO
        - RS
        - RU
        - RW
        - SA
        - SB
        - SC
        - SD
        - SE
        - SG
        - SH
        - SI
        - SJ
        - SK
        - SL
        - SM
        - SN
        - SO
        - SR
        - SS
        - ST
        - SV
        - SX
        - SY
        - SZ
        - TC
        - TD
        - TF
        - TG
        - TH
        - TJ
        - TK
        - TL
        - TM
        - TN
        - TO
        - TP
        - TR
        - TT
        - TV
        - TW
        - TZ
        - UA
        - UG
        - UM
        - UN
        - US
        - UY
        - UZ
        - VA
        - VC
        - VE
        - VG
        - VI
        - VN
        - VU
        - WF
        - WS
        - YE
        - YT
        - ZA
        - ZM
        - ZW